[package]
name = "rusty-cli"
version = "0.1.0"
authors = ["henry <tarou.88@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
